config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_scope :user do
    get "profile", to: "home#profile"
  end
  devise_for :users, controllers: {
    invitations: 'users/invitations',
    registrations: 'users/registrations'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")


    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    namespace :api do
      namespace :v1 do 
        devise_scope :user do
          post "sign_up", to: "registrations#create"
          post "sign_in", to: "sessions#create"
          post 'forgot_password', to: 'passwords#forgot_password'
          post 'reset_password', to: 'passwords#reset_password'
          put 'change_password', to: 'passwords#change_password'
          post "confirm_email", to: "confirmations#confirm_email"
          post "send_invitation", to: "invitations#send_invitation"
          post "send_reinvitation", to: "invitations#send_reinvitation"
          post "accept_invitation", to: "invitations#accept_invitation"
          delete "logout", to: "sessions#logout"
          get "profile", to: "sessions#profile"
        end
  
        # Custom routing error path
        match '*path', to: 'base#routing_error', via: %i[get post put patch delete]
        root to: 'base#routing_error'
      end
    end
    root to: 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Purpleplum</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= javascript_importmap_tags %>
</head>

<body>
  <main>
    <div class="-m-2 mt-3 text-center">
      <% if notice %>
      <div class="p-2">
        <div class="inline-flex items-center bg-white leading-none text-purple-600 rounded-full p-2 shadow text-sm">
          <span
            class="inline-flex bg-purple-600 text-white rounded-full h-6 px-3 justify-center items-center text-">Notice</span>
          <span class="alert alert-success inline-flex px-2"><%= notice %></span>
        </div>
      </div>
      <% end %>
      <% if alert %>
      <div class="p-2">
        <div class="inline-flex items-center bg-white leading-none text-purple-600 rounded-full p-2 shadow text-sm">
          <span
            class="inline-flex  bg-indigo-600  text-white rounded-full h-6 px-3 justify-center items-center text-">Alert</span>
          <span class="alert alert-success inline-flex px-2"><%= alert %></span>
        </div>
      </div>
      <% end %>
    </div>

    <nav class="bg-white shadow-lg">
      <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between">
          <div class="flex space-x-7">
            <div>
              <!-- Website Logo -->
              <a href="#" class="flex items-center py-4 px-2">
                <%= image_tag "profile-image.jpg", class: "h-8 w-8 mr-2" %>
                <span class="font-semibold text-gray-500 text-lg">Purpleplum Demo</span>
              </a>
            </div>
            <!-- Primary Navbar items -->
            <div class="hidden md:flex items-center space-x-1">
            <%= link_to "Home", root_path, class: "py-4 px-2 text-gray-500 font-semibold hover:text-indigo-500 transition duration-300" %>

              <%= link_to "Profile", profile_path, class: "py-4 px-2 text-gray-500 font-semibold hover:text-indigo-500 transition duration-300" %>
              <%= link_to "Invite Staff User", new_user_invitation_path , class: "py-4 px-2 text-gray-500 font-semibold hover:text-indigo-500 transition duration-300" %>

            </div>
          </div>
          <!-- Secondary Navbar items -->
          <div class="hidden md:flex items-center space-x-3 ">

          <% if user_signed_in? %>
            <%= link_to "#{current_user.first_name}", edit_user_registration_path, class: "py-2 px-2 font-medium text-gray-500 rounded hover:bg-indigo-600 hover:text-white transition duration-300 "%>
                <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "py-2 px-2 font-medium text-gray-500 rounded hover:bg-indigo-600 hover:text-white transition duration-300" %>
            <% else %>
                <%= link_to "Sign In", new_user_session_path, class: "py-2 px-2 font-medium text-gray-500 rounded hover:bg-indigo-600 hover:text-white transition duration-300" %>
                <%= link_to "Sign Up", new_user_registration_path, class: "py-2 px-2 font-medium text-gray-500 rounded hover:bg-indigo-600 hover:text-white transition duration-300" %>

            <% end %>
          </div>
          <!-- Mobile menu button -->
          <div class="md:hidden flex items-center">
            <button class="outline-none mobile-menu-button">
              <svg class=" w-6 h-6 text-gray-500 hover:text-indigo-500 " x-show="!showMenu" fill="none"
                stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"
                stroke="currentColor">
                <path d="M4 6h16M4 12h16M4 18h16"></path>
              </svg>
            </button>
          </div>
        </div>
      </div>
      <!-- mobile menu -->
      <div class="hidden mobile-menu">
        <ul class="">
          <li class="active"><a href="index.html"
              class="block text-sm px-2 py-4 text-white bg-indigo-600 font-semibold">Home</a></li>
          <li><a href="#services"
              class="block text-sm px-2 py-4 hover:bg-indigo-600 transition duration-300">Services</a></li>
          <li><a href="#about" class="block text-sm px-2 py-4 hover:bg-indigo-600 transition duration-300">About</a></li>
          <li><a href="#contact" class="block text-sm px-2 py-4 hover:bg-indigo-600 transition duration-300">Contact
              Us</a></li>
        </ul>
      </div>
      <script>
        const btn = document.querySelector("button.mobile-menu-button");
        const menu = document.querySelector(".mobile-menu");

        btn.addEventListener("click", () => {
          menu.classList.toggle("hidden");
        });
      </script>
    </nav>
    <%= yield %>
  </main>
</body>

</html>